### PR TITLE
A7 branch

### PR DESCRIPTION
**Pull request by homeSpatula87**
Assignment 7 branch, hopefully I did this correctly, if not, my bad.

### CODE REVIEW

**Review by greenw0lf — CHANGES_REQUESTED** [review]
I encountered some problems when trying to run your tests that I was not able to solve.

1. In the README, you mention that I need to make sure I satisfy the requirements in ```requirements.txt```. However, there is no requirements.txt file anywhere, and you also listed the requirements above. Those requirements above are packages that are provided by default by any Python3 installation, so you do not have to mention them (and I suggest deleting that line about requirements.txt).
2. You do not explicitly mention which compiler to use or where to look for one. I do not have as much experience with C++ compilers myself, but I was able to find something to use. I installed Visual Studio build tools, which seemed to be enough for the ```cmake ..``` command to execute successfully. It would be nice to explicitly say that you can go to the official documentation page for the library you use for some suggestions, whose URL is listed in the description. Or, mention specifically what compiler one should use, preferably for each OS.
3. Finally, the ```make``` command does not run. I am on Windows 10, I use Visual Studio build tools as the compiler, the cmake command ran just fine, and I installed make by running ```choco install make```. The error I get is:

`make: *** No targets specified and no makefile found.  Stop.`

I looked for the error and it is related to not having a makefile, which I also cannot see in my files after running the previous cmake command. Are you sure it is generated through that command, or perhaps the makefile is indeed missing and had to be pushed? I am not sure how to proceed further on.

4. I also decided to just try to run the test.py file. Unfortunately, it gives this error:

```
Traceback (most recent call last):
  File "D:\pybind11\practice\test.py", line 1, in <module>
    import cpp.build.cpp_tests as cpp
ModuleNotFoundError: No module named 'cpp.build.cpp_tests'
```

I am not sure how to fix it and if it depends on the previous step that did not work for me.

**Comment by homeSpatula87** [comment]
Thank you for reviewing my code.

Your wrote:

_> there is no requirements.txt file anywhere_
My bad, forgot to remove that from the readme.

_> You do not explicitly mention which compiler to use_
Okay, i'll mention some examples.

_>Finally, the ```make``` command does not run_
That is unfortunate. Did CMake add any files to the ```build``` folder? I was expecting it to add a makefile.
It definitely is not the case that the ```make``` file should need to be added.
(The generated make file will for example depend on the path of the build folder)


_>I also decided to just try to run the test.py file._
Yes, unfortunately the library generated seems to be python compiler version and OS dependent (and was generated on Ubuntu on my end), so I would not expect it to work unless the previous step worked.

**Comment by greenw0lf** [comment]
Oh yeah, my bad! I should have attached a picture with my directory after building :D.

image

And this is under the `build` folder.

**Comment by homeSpatula87** [comment]
Okay, so apparently CMake will give different out put based on where you ran it (though I believe mostly it will be a makefile).
But in particular for VisualStudio a .vls file, a "visual studio solution file", when opened, source files are listed, which can be built by right clicking and selecting build. (source: https://youtu.be/6aiV7Z9NRhk?t=82)
Alternatively it seems that, instead of running ```cmake ..```, you can, in VisualStudio, right click the ```CMakeLists.txt``` file, and select "Build all projects". (source: https://youtu.be/sc6_86jgQls?t=216)

Sorry about this, have had no experience with CMake untill this assignment and have never used VisualStudio before.
I'll add extra info to the ```README.md```.

**Comment by greenw0lf** [comment]
I opened `kf_code.sln` in VS and then tried to build using **ALL_BUILD**, but unfortunately it still does not work. This is the error I get, and I tried to look it up, but you already use `#include <numeric>` in the `wrappers.cpp` of the project, which is what most solutions suggest you need to add. This is the output I get when trying to build:

```Build started...
1>------ Build started: Project: cpp_tests, Configuration: Debug x64 ------
1>wrappers.cpp
1>D:\pybind11\practice\cpp\wrappers.cpp(53,17): error C2039: 'transform_reduce': is not a member of 'std'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\iostream(19,1): message : see declaration of 'std'
1>D:\pybind11\practice\cpp\wrappers.cpp(90,66): message : see reference to function template instantiation 'T dot_prod<int>(const std::vector<int,std::allocator<int>> &,const std::vector<int,std::allocator<int>> &)' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>D:\pybind11\practice\cpp\wrappers.cpp(54,1): error C3861: 'transform_reduce': identifier not found
1>Done building project "cpp_tests.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
========== Elapsed 00:01,746 ==========
```

And here's the picture of `wrappers.cpp` inside VS:
image

Let me know if you need more info.

**Comment by homeSpatula87** [comment]
That is unfortunate.
To better understand your issues I have installed Visual Studio 2022, and was able to build the project, and have updated the README to give clearer instructions, and added one line to the CMake file, which might help.

Furthermore I have addressed the previous issues you had with with the README, as well as accommodated for the confusion you had with the instructions (The instructions I gave were too specific, so the confusion was warranted).

**Comment by greenw0lf** [comment]
Yeah, it might be a very weird local machine issue, so I will approve it regardless @s1nayak.

**Review by greenw0lf — APPROVED** [review]

**Comment by homeSpatula87** [comment]
@s1nayak : I know @greenw0lf put in a lot of effort / tried a lot of things for this review.
It was very helpful, as the README turned out not to be fully general at all.
I'd grade him 10/10, would let him review again!

**Comment by homeSpatula87** [comment]
Small update:

I had a dream where I realized I hadn't added any optimization flags to the compilation process of the C++ code (wish that was a joke).

I didn't want to update the code before it was graded, but will state the changes / results here for completeness:

Add ```set(CMAKE_CXX_FLAGS "-O3")``` to CMakeLists.txt

Compiling as usual and running test.py gives the output:
```
Testing class:
('first', 'last') 
 




comparing for loops:
2.578879929072518e+21
cpp for loop time: 2.0013298988342285 

2.6666664666689716e+21
py for loop time: 7.5123515129089355 
 

comparing dot products
cpp conversion time: 6.636517286300659
cpp dot prod total time: 6.722482681274414
cpp dot prod time without conversion: 0.08598446846008301 

np dot prod time: 0.007538318634033203 

results of the dot products: 1000000000.0 1000000000.0
```

Importantly the cpp for loop is now quicker!

**Pull request merged**
